spring.application.name=payment-service

# Payment Configuration
payment.exchange.fee-rate=0.01
payment.exchange.default-rate=0.012
payment.supported-currencies=USD,EUR,INR


# MySQL Database Configuration
spring.datasource.url=jdbc:mysql://localhost:3306/payment_db?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=Balaji@13
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
